from __future__ import annotations
import os
import re
import markdown as md
from html import escape as _escape

_CSS = """
:root { --bg:#0f1720; --card:#16212e; --ink:#e7eef6; --muted:#8ba3ba; --accent:#f5b301; }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
  font:16px/1.6 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif; }
.wrap { max-width: 900px; margin: 0 auto; padding: 40px 24px 80px; }
header { border-bottom: 2px solid var(--accent); padding-bottom: 16px; margin-bottom: 32px; }
h1 { margin:0; font-size: 28px; }
.subtitle { color: var(--muted); margin-top: 6px; }
h2 { margin-top: 40px; font-size: 21px; color: var(--accent);
  border-left: 4px solid var(--accent); padding-left: 12px; }
table { width:100%; border-collapse: collapse; margin: 16px 0;
  background: var(--card); border-radius: 8px; overflow: hidden; }
th,td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #24344a; }
th { background:#1d2c3d; color: var(--ink); }
code { background:#0b1219; padding:2px 5px; border-radius:4px; }
footer { margin-top: 56px; color: var(--muted); font-size: 13px;
  border-top: 1px solid #24344a; padding-top: 16px; }
[dir=rtl] { text-align: right; }
[dir=rtl] h2 { border-left: 0; border-right: 4px solid var(--accent);
  padding-left: 0; padding-right: 12px; }
"""

_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title><style>{css}</style></head>
<body><div class="wrap">
<header><h1>{title}</h1><div class="subtitle">{subtitle}</div></header>
{body}
<footer>Generated by solar-analysis · figures computed in Python, narrative by Claude.</footer>
</div></body></html>"""

def render_html(report_md: str, title: str, subtitle: str) -> str:
    body = md.markdown(report_md, extensions=["tables", "fenced_code", "md_in_html"])
    return _TEMPLATE.format(title=title, subtitle=subtitle, css=_CSS, body=body)

# Email-safe rendering: mail clients (Outlook's Word engine, Gmail) do not
# support CSS custom properties and don't reliably honor <head><style>, so the
# email body uses a light theme with styles inlined onto each element.
_EMAIL_BODY_STYLES = {
    "h1": "margin:0;font-size:24px;color:#12202e;",
    "h2": "margin:28px 0 8px;font-size:19px;color:#a86500;",
    "h3": "margin:20px 0 6px;font-size:16px;color:#12202e;",
    "p": "margin:12px 0;color:#1a2330;font-size:15px;line-height:1.6;",
    "table": "width:100%;border-collapse:collapse;margin:16px 0;font-size:14px;",
    "th": "padding:9px 12px;text-align:left;background:#eef2f6;color:#12202e;border:1px solid #d5dde5;",
    "td": "padding:9px 12px;text-align:left;color:#1a2330;border:1px solid #d5dde5;",
    "ul": "margin:12px 0;padding-left:22px;color:#1a2330;font-size:15px;line-height:1.6;",
    "ol": "margin:12px 0;padding-left:22px;color:#1a2330;font-size:15px;line-height:1.6;",
    "li": "margin:4px 0;",
    "code": "background:#eef2f6;padding:2px 5px;border-radius:4px;font-family:Consolas,monospace;font-size:13px;",
    "a": "color:#a86500;",
}
_EMAIL_TAG_RE = re.compile(r"<(h1|h2|h3|p|table|th|td|ul|ol|li|code|a)(\s[^>]*)?>")

def _inline_email_styles(html: str) -> str:
    def repl(m):
        tag, attrs = m.group(1), m.group(2) or ""
        if "style=" in attrs:
            return m.group(0)
        return f'<{tag}{attrs} style="{_EMAIL_BODY_STYLES[tag]}">'
    return _EMAIL_TAG_RE.sub(repl, html)

_EMAIL_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f6f8;font-family:Segoe UI,Arial,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f8;">
<tr><td align="center" style="padding:24px 12px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;">
<tr><td style="padding:32px 28px;">
<h1 style="margin:0;font-size:24px;color:#12202e;">{title}</h1>
<div style="color:#5b6b7b;margin-top:6px;font-size:14px;">{subtitle}</div>
<div style="border-bottom:2px solid #f5b301;margin:16px 0 24px;font-size:0;line-height:0;">&nbsp;</div>
{body}
<div style="margin-top:40px;color:#5b6b7b;font-size:12px;border-top:1px solid #d5dde5;padding-top:16px;">Generated by solar-analysis · figures computed in Python, narrative by Claude.</div>
</td></tr></table>
</td></tr></table>
</body></html>"""

def render_email_html(report_md: str, title: str, subtitle: str) -> str:
    """Light-theme, inline-styled HTML body for email clients (no CSS
    variables, no reliance on <head> styles). Mirrors render_html's content
    but survives Outlook/Gmail. The on-disk report still uses render_html."""
    body = _inline_email_styles(md.markdown(
        report_md, extensions=["tables", "fenced_code", "md_in_html"]))
    return _EMAIL_TEMPLATE.format(title=title, subtitle=subtitle, body=body)

def write_report(html: str, out_dir: str) -> str:
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "report.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path

def write_dashboard(html: str, out_dir: str) -> str:
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "dashboard.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path

def append_unavailable_section(report_md: str, skipped: list[dict]) -> str:
    if not skipped:
        return report_md
    lines = "\n".join(f"- **{_escape(s['name'])}**: {_escape(s['reason'])}"
                      for s in skipped)
    return (report_md + "\n\n## Unavailable Plants\n\nThe following plants "
            "could not be fetched for this run:\n\n" + lines)

def prepend_summary(report_md: str, summary_md: str) -> str:
    """Put a Hebrew executive summary ("סיכום מנהלים") at the top of the report,
    in a right-to-left block, above the detailed analysis. The `markdown="1"`
    div + blank line lets the md_in_html extension render the inner markdown."""
    return ('<div dir="rtl" markdown="1">\n\n'
            '## סיכום מנהלים\n\n'
            f'{summary_md}\n\n'
            '</div>\n\n---\n\n' + report_md)
