from __future__ import annotations
import os
import markdown as md

_CSS = """
:root { --bg:#0f1720; --card:#16212e; --ink:#e7eef6; --muted:#8ba3ba; --accent:#f5b301; }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
  font:16px/1.6 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif; }
.wrap { max-width: 900px; margin: 0 auto; padding: 40px 24px 80px; }
header { border-bottom: 2px solid var(--accent); padding-bottom: 16px; margin-bottom: 32px; }
h1 { margin:0; font-size: 28px; }
.subtitle { color: var(--muted); margin-top: 6px; }
h2 { margin-top: 40px; font-size: 21px; color: var(--accent);
  border-left: 4px solid var(--accent); padding-left: 12px; }
table { width:100%; border-collapse: collapse; margin: 16px 0;
  background: var(--card); border-radius: 8px; overflow: hidden; }
th,td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #24344a; }
th { background:#1d2c3d; color: var(--ink); }
code { background:#0b1219; padding:2px 5px; border-radius:4px; }
footer { margin-top: 56px; color: var(--muted); font-size: 13px;
  border-top: 1px solid #24344a; padding-top: 16px; }
"""

_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title><style>{css}</style></head>
<body><div class="wrap">
<header><h1>{title}</h1><div class="subtitle">{subtitle}</div></header>
{body}
<footer>Generated by solar-analysis · figures computed in Python, narrative by Claude.</footer>
</div></body></html>"""

def render_html(report_md: str, title: str, subtitle: str) -> str:
    body = md.markdown(report_md, extensions=["tables", "fenced_code"])
    return _TEMPLATE.format(title=title, subtitle=subtitle, css=_CSS, body=body)

def write_report(html: str, out_dir: str) -> str:
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "report.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path
